// ============================================================
// AI 数据中心可视化 — 数据层 V2 (2026-06-11)
// 所有数字、文案、玩家信息都在这个文件里，后续更新只改这里。
//
// V2 变更：
//  - 主数据源升级为 Bernstein 2026-06-08《AI Value Chain: How much
//    does a GW of Vera Rubin data center capacity actually cost?》
//    Exhibit 1/5/6：H100 DGXx8 / GB200 NVL72 / VR NVL72 三代对照
//  - GB200 整柜 $3.4M→$4.3M（存储 $85K→$832K，NAND 自 2023/4 低点涨 11.3 倍）
//  - VR NVL72 详细化：$9.1M/柜、$47B/GW（HBM4 按 $53/GB 计入 $1.09M）
//  - 物理结构按 SemiAnalysis《GB200 Hardware Architecture》(2024-07)
//    与 NVIDIA DGX 文档/OCP 规格校准
//  - 园区冷却链路按 SemiAnalysis《Datacenter Anatomy Part 2 Cooling》
//    与 Vertiv 360AI RD#020 校准
// 旧 V1 基准（Bernstein 2025-10-27 GB200 口径）已被覆盖，见 git 历史
//
// 置信度: A=报告表格原文  B=报告正文  C=公开常识/待校准
// ============================================================

export const META = {
  source: 'Bernstein 2026-06-08 (VR/GB200/H100 三代对照) + SemiAnalysis 物理规格',
  asOf: '2026-06-08',
};

// 三代机柜对照表（Bernstein Exhibit 5/6）
export const ARCH_COMPARE = {
  headers: ['', 'H100 DGX×8', 'GB200 NVL72', 'VR NVL72'],
  rows: [
    ['整柜价格 ($M)', '2.0', '4.3', '9.1'],
    ['机柜功率 (kW)', '41', '132', '220'],
    ['每 GW 机柜数', '12,175', '5,929', '3,557'],
    ['DC capex ($B/GW)', '37.0', '40.5', '47.3'],
    ['FP8 算力/柜 (PFLOPS)', '256', '720', '2,520'],
    ['每 $B capex 算力 (EFLOPS)', '84', '106', '189'],
  ],
};

// ------------------------------------------------------------
// 数据中心全景层（园区）：每 GW capex 拆分（GB200 口径，机柜外部分三代通用）
// 机柜外合计 $15B/GW（机电 11.2 + 土地 3.8），来自 Bernstein；
// 细项拆分沿用 2025-10 报告 Exhibit 2（两份报告口径一致）
// ------------------------------------------------------------
export const CAMPUS_TOTAL_BGW = 40.5; // GB200 口径全口径 $B/GW

export const CAMPUS_ZONES = [
  {
    id: 'whitespace',
    name: '机房白区（IT 机柜）',
    perRackK: 4296, bGW: 25.5, pct: 63.0, conf: 'A',
    desc: '放服务器机柜的主机房。GB200 口径下机柜占全口径 capex 的 63%（VR 时代升到 68%）。Vertiv 参考设计里一个 7MW 数据厅是 48 个 130kW 计算柜 + 48 个 14kW 支持柜。点进去看机柜内部拆分。',
    role: '承载全部计算、网络、存储设备',
    players: ['（见机柜内部各部件）'],
    action: 'enterRack',
  },
  {
    id: 'power-distribution',
    name: '配电系统（电力链路）',
    perRackK: 587, bGW: 3.5, pct: 8.6, conf: 'A',
    desc: '电力链路完整 8 段：①现场变电站（HV→MV，230kV→33kV）②中压开关柜 ③中压变压器（2.5-3MVA，33/22/11kV→415V）④ATS 自动切换 ⑤低压开关柜 ⑥UPS+BBU ⑦STS 静态旁路 ⑧PDU/母线槽到机柜。点击右图链路上每个方块看细节。AI 数据中心机柜密度从传统 <10kW 跃迁到 130kW+（50 倍），所有环节都被推到极限——HV 变压器交付期已超 12 个月，GOES 取向硅钢成为产业瓶颈。',
    role: '电从电网到机柜的全链路',
    players: ['伊顿', '施耐德', 'Vertiv', 'ABB', '台达', '金盘科技(C)'],
    children: [
      { name: '变压器（HV+MV）', perRackK: 306 },
      { name: '中低压开关柜', perRackK: 110 },
      { name: '电缆', perRackK: 93 },
      { name: '母线槽 Busway', perRackK: 50 },
      { name: 'PDU/ATS/STS 等', perRackK: 29 },
    ],
  },
  {
    id: 'backup-power',
    name: '备用电源（UPS + BBU + 柴发）',
    perRackK: 272, bGW: 1.6, pct: 4.0, conf: 'A',
    desc: '三段式备份：UPS 应对毫秒级断电（响应 <10ms），柴发应对长时段（启动需 60s，满载续航 24-48 小时），BBU 走机柜内部路线绕过中央 UPS。AI 时代的结构性变化是 BBU 渗透——锂电池放进机柜本身就是 in-rack UPS，电池容量减半，效率更高，是 Rubin 时代电源价值量上修 3 倍的核心驱动之一（代价：机柜内消防方案要重做）。冗余口径：UPS/PDU 通常做 2N（A/B 双路），变压器/柴发做 N+1，对应 Tier 3 标准。',
    role: '断电时电力的多级冗余',
    players: ['伊顿', '施耐德', 'Vertiv', '台达', '柴发：卡特彼勒/康明斯/Rolls-Royce MTU'],
    children: [
      { name: 'UPS 硬件', perRackK: 258 },
      { name: '电池备份单元 BBU', perRackK: 14 },
    ],
  },
  {
    id: 'generators',
    name: '柴油/燃气发电机',
    perRackK: 365, bGW: 2.2, pct: 5.4, conf: 'A',
    desc: '长时间停电的冗余电源，经 ATS（自动切换开关）接入配电链路，通常是一排集装箱式机组。注意：电网级燃气轮机（GE Vernova、西门子能源、三菱重工，合计全球产能 70-80%）不在数据中心 capex 口径内，但是当前最大的产业瓶颈。',
    role: '长时间断电的兜底冗余',
    players: ['卡特彼勒', '康明斯', '劳斯莱斯 MTU', '科勒', 'Generac'],
  },
  {
    id: 'thermal',
    name: '热管理（机房级冷却链路）',
    perRackK: 211, bGW: 1.3, pct: 3.2, conf: 'A',
    desc: '完整热链路：芯片冷板→托盘歧管(CDM)→机柜→CDU（液-液换热，单台 >1MW）→设施水管路→冷机(chiller，单台可达 15-20MW)→冷却塔排到大气。冷机是数据中心除 IT 外最耗电的设备（占非 IT 耗电 60-80%）。Vertiv 7MW 参考设计：72% 直达芯片液冷 + 28% 周边风冷。',
    role: '把芯片的热搬到大气里',
    players: ['Vertiv', 'Johnson Controls(C)', '英维克(C)', '申菱环境(C)', '台达', 'Stulz(C)'],
    children: [
      { name: '风冷（CRAH 等）', perRackK: 110 },
      { name: '液冷（CDU/管路）', perRackK: 44 },
      { name: '配套设施', perRackK: 57 },
    ],
  },
  {
    id: 'other-infra',
    name: '其他物理基础设施',
    perRackK: 459, bGW: 2.7, pct: 6.7, conf: 'A',
    desc: '管道/水泵/机器人等杂项、DCIM 软件与传感器、物理安防、消防、KVM、天花板地板、照明等。',
    role: '机房正常运转的各种配套',
    players: ['分散，无集中玩家'],
    children: [
      { name: '管道、泵、机器人等', perRackK: 319 },
      { name: 'DCIM 软件与传感器', perRackK: 55 },
      { name: '安防/消防/其他', perRackK: 85 },
    ],
  },
  {
    id: 'land',
    name: '土地与建筑',
    perRackK: 636, bGW: 3.8, pct: 9.4, conf: 'A',
    desc: '地皮和厂房本身。折旧周期最长（10-25 年），从真实经济成本（TCO）看权重比现金 capex 显示的更低——IT 硬件按 6 年折旧，一个 GW 的年折旧约 $7.9B（VR 口径），是主导性的运营成本。',
    role: '物理载体',
    players: ['开发商/REITs：Equinix、Digital Realty、万国数据(C)'],
  },
];

// ------------------------------------------------------------
// 机柜方案（可切换）
// ------------------------------------------------------------
export const RACK_TYPES = {
  gb200: {
    id: 'gb200',
    name: 'NVIDIA GB200 NVL72',
    short: 'GB200',
    status: 'detailed',
    rackPriceK: 4296, pctOfDC: 63.0, conf: 'A',
    tagline: '72 颗 Blackwell GPU + 36 颗 Grace CPU，单柜 132kW 全液冷，当前部署主力。2026-06 报告把整柜上修到 $4.3M（旧口径 $3.4M）——主因是存储：NAND 价格自 2023 年 4 月低点涨了 11.3 倍，柜内 2.2PB NVMe 从 $85K 变成 $832K。',
    spec: '物理结构（SemiAnalysis/NVIDIA/OCP）：48RU、600×1068×2236mm、承重 1.6 吨级；18 个 1U 计算托盘（每个 2 块 Bianca 板 = 2 Grace + 4 Blackwell）+ 9 个 NVSwitch 托盘（中部）+ 4 个 33kW 电源架（顶 2 底 2 对称）+ 顶部管理 TOR；后部：1200A 48V 直流母排 + 液冷歧管 + 5184 根 NVLink 铜缆背板。',
  },
  rubin: {
    id: 'rubin',
    name: 'NVIDIA Vera Rubin NVL72',
    short: 'VR NVL72',
    status: 'detailed',
    rackPriceK: 9093, pctOfDC: 68.3, conf: 'A',
    tagline: '2026H2 起的下一代：整柜 $9.1M（媒体说的 $8M 用的是过时内存价）。Rubin GPU 单价 $55K×72 = $396 万占近一半；HBM4 按 2027 年 $53/GB 算贡献 $1.09M（涨价是上修的最大驱动）；内存+存储合计 ~$3.2M（占 35%）。算力 2520 PFLOPS = GB200 的 3.5 倍，每美元算力仍在加速。',
    spec: '220kW/柜（GB200 的 1.7 倍），3557 柜/GW，$47B/GW。结构与 NVL72 同族；电源价值量 $150K（GB200 的 3 倍+），800V HVDC 一代预计 2H26 部署；SOCAMM LPDDR5X 54TB（内存容量 +320%）。',
  },
  h100: {
    id: 'h100',
    name: 'H100 DGX ×8（上代对照）',
    short: 'H100',
    status: 'brief',
    rackPriceK: 2026, pctOfDC: null, conf: 'A',
    tagline: '上一代风冷方案：一柜约 8 台 HGX 服务器 64 颗 GPU，41kW 风冷（3D 均热腔+风扇，9-10RU 高的服务器）。对照看演进：单柜价值 $2M→$4.3M→$9.1M，功率 41→132→220kW，算力每 $B capex 84→106→189 EFLOPS——越贵越值。',
    spec: '服务器级参考架构（非机柜级），机柜形态差异较大；风冷是它和 NVL72 的本质区别',
  },
  gb300: {
    id: 'gb300',
    name: 'NVIDIA GB300 NVL72',
    short: 'GB300',
    status: 'brief',
    rackPriceK: null, pctOfDC: null, conf: 'C',
    tagline: 'GB200 升级款（B300 GPU、HBM3e 288GB/颗）。结构与电源规格与 GB200 相近；BBU 渗透率提升使单柜电源价值量到约 $46K。整柜价格待材料校准（介于 GB200 与 VR 之间）。',
    spec: '结构与 GB200 NVL72 基本一致',
  },
  tpu: {
    id: 'tpu',
    name: 'Google TPU 机柜',
    short: 'TPU',
    status: 'framework',
    rackPriceK: null, pctOfDC: null, conf: 'C',
    tagline: '自研 ASIC 路线代表。TPU 由 Google 设计、博通（部分转联发科）做后端，台积电代工；机柜间用 OCS 光交换组网。ASIC 毛利率 ~50%（vs 英伟达 70%+），同样 capex 能买到约 19% 更多算力。具体 BOM 待你给材料。',
    spec: '示意结构：TPU 托盘 + ICI 互联 + OCS 光路交换',
  },
  ascend: {
    id: 'ascend',
    name: '华为昇腾 CloudMatrix 384',
    short: '昇腾',
    status: 'framework',
    rackPriceK: null, pctOfDC: null, conf: 'C',
    tagline: '国产链代表。384 颗昇腾 910C，16 柜组成超节点（12 计算柜 + 4 交换柜），全光互联换规模。公开估算整系统 $8M 级别，待校准。',
    spec: '示意结构：16 柜超节点',
  },
  cpu: {
    id: 'cpu',
    name: '通用 CPU 服务器机柜（对照）',
    short: 'CPU柜',
    status: 'framework',
    rackPriceK: 400, pctOfDC: null, conf: 'C',
    tagline: '传统数据中心机柜：约 20 台 2U 双路 x86，10-15kW 风冷，整柜 $30-50 万 ≈ GB200 柜的 1/10、VR 柜的 1/20。',
    spec: '约 20× 2U 双路服务器 + TOR 交换机',
  },
};

// 各架构整柜 BOM 表（Bernstein 2026-06-08 Exhibit 1，$K/柜）
export const RACK_BOM = {
  gb200: [
    { id: 'cpu', name: 'CPU（含 LPDDR $252K）', perRackK: 345 },
    { id: 'gpu', name: 'GPU（含 HBM $185K）', perRackK: 2297 },
    { id: 'nvlink-domain', name: 'Scale-up 小计（NVSwitch+铜缆+背板）', perRackK: 287 },
    { id: 'network-rack', name: 'Scale-out（SpectrumX+以太网）', perRackK: 341 },
    { id: 'e1s-storage', name: '直连存储 2.2PB NVMe', perRackK: 832 },
    { id: 'manifold', name: '柜内液冷', perRackK: 51 },
    { id: 'rack-frame', name: '机箱 Chassis', perRackK: 100 },
    { id: 'power-shelf', name: '电源（4×33kW 电源架等）', perRackK: 44 },
  ],
  rubin: [
    { id: 'cpu', name: 'Vera CPU（含 LPDDR $802K）', perRackK: 982 },
    { id: 'gpu', name: 'Rubin GPU（含 HBM4 $1,093K）', perRackK: 5053 },
    { id: 'nvswitch-tray', name: 'NVLink 交换托盘', perRackK: 253 },
    { id: 'copper-backplane', name: '铜缆 $238K + 背板等 $380K', perRackK: 618 },
    { id: 'network-rack', name: 'Scale-out（SpectrumX+以太网）', perRackK: 396 },
    { id: 'e1s-storage', name: '直连存储 3.5PB NVMe', perRackK: 1282 },
    { id: 'manifold', name: '柜内液冷', perRackK: 158 },
    { id: 'rack-frame', name: '机箱 + 其他', perRackK: 200 },
    { id: 'power-shelf', name: '电源（800V HVDC 方向）', perRackK: 150 },
  ],
  h100: [
    { id: 'cpu', name: 'CPU（含 DRAM $238K）', perRackK: 271 },
    { id: 'gpu', name: 'H100 GPU（含 HBM $65K）', perRackK: 1519 },
    { id: 'copper-backplane', name: 'Scale-up（柜内 NVLink）', perRackK: 112 },
    { id: 'network-rack', name: 'Scale-out', perRackK: 22 },
    { id: 'e1s-storage', name: '直连存储', perRackK: 102 },
  ],
};

// ------------------------------------------------------------
// 部件库：所有可点击物体的信息
// value 口径（GB200 基准）：perRackK = $K/整柜, bGW = $B/GW, pct = 占 DC capex %
// vrK = VR NVL72 口径的 $K/柜（有意义时填写）
// ------------------------------------------------------------
export const COMPONENTS = {
  // ===== 机柜层 =====
  'compute-tray': {
    name: '计算托盘（Compute Tray）',
    cat: '机柜单元',
    desc: '1U 高的"刀片"，全柜 18 个。每个装 2 块 Bianca 板（每板 1 Grace CPU + 2 Blackwell GPU），单托盘 TDP 6.3kW。托盘约 85% 热量走液冷（Bianca 板上盖冷板），前部 NIC/DPU/管理板仍是风冷（8 个风扇）。前面板：8 个 E1.S 存储位 + OSFP 笼 + 管理口。点击进入托盘内部。',
    role: '算力的物理载体',
    shape: '1U 抽屉式金属托盘；内部两块 Bianca 板上盖液冷冷板，前部是存储位和网络接口',
    value: { perRackK: 2642, bGW: 15.7, pct: 38.7 }, vrK: 6035,
    valueNote: '计算小计（CPU+GPU 含内存与毛利）；VR $6.0M',
    players: ['ODM 组装：鸿海、广达、纬创', '品牌：Dell、HPE、SMCI'],
    conf: 'A',
    action: 'enterTray',
  },
  'nvswitch-tray': {
    name: 'NVSwitch 交换托盘',
    cat: '机柜单元',
    desc: '柜内 9 个（位于机柜中部），每个含 2 颗 28.8Tb/s NVSwitch5 芯片，把 72 颗 GPU 用 NVLink 连成一个"大 GPU"（scale-up）。NVL72 的交换托盘不需要跨柜互联，所以前面板没有光模块笼（NVL36×2 才有）。',
    role: 'GPU 之间的柜内高速互联',
    shape: '1U 托盘，两颗大芯片在中间压着冷板，背面是高密度背板连接器',
    value: { perRackK: 184, bGW: 1.1, pct: 2.7 }, vrK: 253,
    valueNote: '交换托盘合计（芯片+设计+整机毛利）；VR $253K',
    players: ['NVIDIA（芯片与设计）', '代工：台积电'],
    conf: 'A',
    action: 'enterSwitchTray',
  },
  'power-shelf': {
    name: '电源架（Power Shelf）×4',
    cat: '机柜单元',
    desc: 'NVL72 有 4 个电源架，顶部 2 个 + 底部 2 个对称布置。每个 = 6 颗 5.5kW PSU = 33kW，合计 132kW。输入 346-480V 交流（来自机房 power whip），输出 48/50V 直流给母排，单架最大 600A。机柜级集中整流比节点级 PSU 效率高约 2%。VR 时代电源价值量涨到 $150K（3 倍+），800V HVDC 在 2H26 启动——这是确定性最强的增量环节。',
    role: 'AC→DC 整流与柜内供电',
    shape: '1U 金属盒，里面 6 个可热插拔电源模块',
    value: { perRackK: 44, bGW: 0.3, pct: 0.6 }, vrK: 150,
    valueNote: 'VR $150K（+240%）；VRM 主力：MPS、瑞萨、英飞凌',
    players: ['台达', '光宝', 'Vicor', '麦格米特(C)', '欧陆通(C)'],
    conf: 'A',
  },
  'busbar': {
    name: '直流母排（Busbar）',
    cat: '机柜单元',
    desc: '机柜后部垂直贯通的铜排，48V 直流、载流 1200A。4 个电源架把电送上母排，每个托盘背后的盲插连接器从母排取电，托盘内 PDB 再把 48V 降到 12V 给 Bianca 板。集中母排是 NVL72 供电架构的核心（替代每台服务器自带 PSU）。',
    role: '柜内供电主干',
    shape: '机柜背部一根贯通上下的铜质扁排',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入电源/机箱项；800V HVDC 时代母排载流与价值量都会显著提升',
    players: ['伊顿', 'Molex(C)', '台达', 'Starline(C)'],
    conf: 'B',
  },
  'manifold': {
    name: '液冷歧管 + 冷板系统',
    cat: '机柜单元',
    desc: '柜内液冷回路：垂直歧管（蓝=进水/红=回水）经快接头（QD）连到每个托盘的分配歧管（CDM），冷却液流过芯片上的冷板把热带走，汇集后送往机房 CDU。Bianca 板 2700W 只有液冷能压住——这是 NVL72 全液冷的根本原因。',
    role: '芯片级散热（柜内段）',
    shape: '机柜后侧两根垂直管 + 每托盘的冷板和软管',
    value: { perRackK: 51, bGW: 0.3, pct: 0.7 }, vrK: 158,
    valueNote: 'VR $158K（+210%）；L2L（液-液）方案比 L2A（液-气 sidecar）经济得多',
    players: ['Vertiv', '台达', '奇鋐(C)', '双鸿(C)', '英维克(C)', 'CoolerMaster(C)'],
    conf: 'A',
  },
  'copper-backplane': {
    name: 'NVLink 铜缆背板',
    cat: '机柜单元',
    desc: '柜子后部的"电缆墙"：精确地说是 5184 根同轴铜缆（72 GPU × 72 对差分线，每根 200Gb/s 单向）把计算托盘和交换托盘全部直连。如果用光模块替代，需要 648 个 1.6T 收发器 ≈ $55 万成本（客户价 $220 万）外加 20kW 功耗——这就是铜赢的原因，也是 DGX H100 NVL256 没出货的原因。',
    role: '柜内 scale-up 互联的物理介质',
    shape: '机柜背面密密麻麻的黑色缆束（cable cartridge）和连接器矩阵',
    value: { perRackK: 225, bGW: 1.3, pct: 3.3 }, vrK: 618,
    valueNote: 'GB200：铜缆 $123K + 背板 $102K（注：报告 scale-up 小计 $287K 与细项加总存在口径差）；VR：$238K + $380K，接近 3 倍',
    players: ['安费诺 Amphenol', '立讯精密(C)', 'TE(C)', '沃尔核材/瑞可达(C)'],
    conf: 'A',
  },
  'e1s-storage': {
    name: '直连存储（E1.S NVMe）',
    cat: '机柜单元',
    desc: 'V2 大变化：每个计算托盘前面板 8 个 E1.S 盘位（15.36TB）+ 1 个 M.2 启动盘，全柜 2.2PB NAND。NAND 价格从 2023 年 4 月低点涨了 11.3 倍，这项从旧口径 $85K 暴涨到 $832K（占 capex 12%）——存储从"忽略不计"变成第三大件。VR 加 ICMS 后 3.5PB、$1.28M。运营商不愿换 HDD：性能下降会加重本就稀缺的内存负担，且 HDD 体积功耗更大。',
    role: '训练数据与 checkpoint 的本地高速存储',
    shape: '托盘前面板一排小竖条盘位；外部冷存储（80% 容量按 GB 计）在独立存储阵列走 HDD',
    value: { perRackK: 832, bGW: 4.9, pct: 12.2 }, vrK: 1282,
    valueNote: 'TLC NAND 按 $0.37/GB（含 30% AI 溢价）；价格波动大，需常更新',
    players: ['NAND：三星、SK海力士、美光、闪迪/Solidigm', '外部阵列 HDD：希捷、西数'],
    conf: 'A',
  },
  'rack-frame': {
    name: '机柜框架与机械件',
    cat: '机柜单元',
    desc: '柜体钢结构、滑轨、托盘底盘等。OCP MGX 规格：48RU，600mm 宽 × 1068mm 深 × 2236mm 高（可加深到 1200mm），承重 1600kg，支持盲插歧管、前部预留互连线缆区。',
    role: '结构件',
    shape: '比标准 19" 柜更深更重的 21" OCP 柜',
    value: { perRackK: 100, bGW: 0.6, pct: 1.5 }, vrK: 100,
    valueNote: 'Chassis 项；机柜其他杂项 VR 另有 ~$100K',
    players: ['鸿海', '广达', '纬创', 'Cheval(C)', '奇鋐(C)'],
    conf: 'A',
  },
  'tor-switch': {
    name: '管理 TOR 交换机',
    cat: '机柜单元',
    desc: '机柜顶部 2 台管理交换机（NVIDIA DGX 文档），走带外管理网（OOB）：BMC 遥测、固件、电源/CDU 监控都在这张网上。全柜有 51-87 颗 BMC 芯片（每计算托盘 2-4 颗 + 交换托盘/电源架各 1 颗）。',
    role: '带外管理网络',
    shape: '柜顶 1U 交换机',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入网络杂项；BMC 主要玩家 ASPEED(C)',
    players: ['NVIDIA/第三方以太网交换机', 'BMC：ASPEED(C)'],
    conf: 'B',
  },

  // ===== 机柜旁 =====
  'network-rack': {
    name: '网络机柜（Scale-out）',
    cat: '配套机柜',
    desc: '柜外组网：SpectrumX/InfiniBand 交换机 + 光模块把几千个机柜连成集群。GB200 口径 scale-out $341K/柜（SpectrumX 交换机 $188K + 以太网 fabric $154K）。超大客户最常见的"偏离参考设计"就是把 SpectrumX TOR 换成第三方（博通方案）交换机。双击进入集群网络视图。',
    role: '机柜之间、集群层面的互联',
    shape: '独立机柜装满交换机，前面板全是光模块端口',
    value: { perRackK: 341, bGW: 2.0, pct: 5.0 }, vrK: 396,
    valueNote: '网络合计（scale-up+out）约占机柜成本 13%：8% scale-up + 5% scale-out',
    players: ['交换机：NVIDIA、Arista、思科(C)', '交换芯片：博通', '光模块：中际旭创、新易盛、Coherent(C)'],
    conf: 'A',
    action: 'enterCluster',
  },

  // ===== 托盘层 =====
  'gpu': {
    name: 'GPU（Blackwell B200）',
    cat: '芯片',
    desc: '价值量的绝对核心：GB200 口径 GPU 合计 $2.3M/柜（占 capex 34%）；VR 口径 Rubin GPU $55K/颗 ×72 = $3.96M，仅 GPU 就占整柜近一半。每颗 B200 两个 reticle 极限 die + 8 颗 HBM3e，TSMC 4NP + CoWoS 封装。',
    role: '训练/推理的算力本体',
    shape: '名片大小的基板封装：中间两块大 die、四周 HBM，上面压液冷冷板',
    value: { perRackK: 2297, bGW: 13.6, pct: 33.6 }, vrK: 5053,
    valueNote: 'GB200 ≈$32K/颗（含 HBM 与毛利）；Rubin $55K/颗（双 die 单封装按颗计）',
    players: ['设计：NVIDIA（替代：AMD MI）', '代工：台积电'],
    conf: 'A',
  },
  'hbm': {
    name: 'HBM（高带宽内存）',
    cat: '芯片',
    desc: '堆叠 DRAM，紧贴 GPU die 封装，提供 TB/s 级带宽。GB200 全柜 13.4TB HBM3e（$185K）；VR 全柜 20.7TB HBM4——按 2027 年量产价 $48/GB + 英伟达 ~10% 加价 = $53/GB，贡献 $1.09M/柜，是 VR 整柜上修到 $9.1M 的最大单一驱动。',
    role: 'GPU 的"工作内存"，带宽决定算力发挥',
    shape: 'GPU 大 die 旁边的小方块，8-12 层 DRAM 垂直堆叠',
    value: { perRackK: 185, bGW: 1.1, pct: 2.7 }, vrK: 1093,
    valueNote: 'HBM4 现价 $16.6/GB → 2027E $53/GB（含加价）；价格波动需跟踪',
    players: ['SK海力士（主供）', '美光', '三星'],
    conf: 'A',
  },
  'cpu': {
    name: 'CPU（Grace / Vera）',
    cat: '芯片',
    desc: 'Arm 服务器 CPU，每块 Bianca 板 1 颗（配 2 GPU）。Vera CPU 单价约 $5K。大头其实是它带的内存：GB200 全柜 17TB LPDDR5X（$252K）；VR 暴增到 54TB（+320%），SOCAMM 形态比手机 LPDDR 溢价 30%（$14.85/GB），贡献 $802K。LPDDR 短缺可能反过来限制 VR 出货。',
    role: 'GPU 的管家：喂数据、跑系统、扩展内存',
    shape: '与 GPU 同板的另一颗大芯片，旁边一圈 LPDDR 颗粒',
    value: { perRackK: 345, bGW: 2.0, pct: 5.0 }, vrK: 982,
    valueNote: 'GB200：芯片 $92K + DRAM $252K；VR：$180K + $802K',
    players: ['NVIDIA（Arm 架构）', 'LPDDR：美光、三星、SK海力士'],
    conf: 'A',
  },
  'nic': {
    name: '网卡 NIC（ConnectX-7/8）',
    cat: '芯片/板卡',
    desc: '每托盘 4 张 ConnectX mezzanine 卡（Pegatron 规格：4× CX-7 400G OSFP），负责 scale-out 后端网络。托盘内成本大头是连接 mezz 板的 Mirror 连接器和通到前面板 OSFP 笼的 DensiLink 缆。',
    role: '托盘对外的网络出口',
    shape: '托盘前部小卡 + 前面板 OSFP 笼',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入 scale-out 项',
    players: ['NVIDIA（ConnectX）', '博通(C)'],
    conf: 'B',
  },
  'dpu': {
    name: 'DPU（BlueField-3）',
    cat: '芯片/板卡',
    desc: '参考设计每托盘 2 颗 BlueField-3 做前端网络卸载——但 SemiAnalysis 判断多数客户根本不会配 BF-3（或只配 1 颗），自建 Nitro 类方案或纯 NIC 更划算。看到 DPU 收入时注意打折。',
    role: '网络/存储/安全任务的卸载引擎（可选件）',
    shape: '类似网卡的板卡，带 Arm 核大芯片',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '参考设计含、实际部署常砍——价值量计入 scale-out 项',
    players: ['NVIDIA（BlueField）', 'AWS Nitro（自用）(C)'],
    conf: 'B',
  },
  'coldplate': {
    name: '液冷冷板 + 快接头',
    cat: '散热',
    desc: '铜板直压芯片，微通道液体带走热量；快接头（UQD）让托盘可以不漏液地热插拔。一块 Bianca 板 2700W 全靠它。供应链：冷板（奇鋐/双鸿/Boyd）、UQD（Staubli/CPC 等）、CDM 歧管。',
    role: '芯片表面的直接换热器',
    shape: '覆盖芯片的金属板 + 进出水软管 + 盲插快接头',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入柜内液冷项（GB200 $51K / VR $158K）',
    players: ['奇鋐', '双鸿', 'Boyd(C)', 'CoolerMaster', 'UQD：Staubli(C)、CPC(C)'],
    conf: 'B',
  },
  'pcb': {
    name: 'Bianca 主板 + 封装基板',
    cat: '板材',
    desc: '托盘核心是 2 块 Bianca 板（1 Grace + 2 Blackwell 直焊），高层数 HDI；GPU 下面还有 ABF 载板。板上 VRM（供电模块）主力是 MPS、瑞萨、英飞凌；PDB（配电板）供应商分散。Bernstein 认为基板含量持续增长，看好 Ibiden 和欣兴。',
    role: '所有芯片的物理连接层',
    shape: '黑色大板子，芯片、VRM、连接器都在上面',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '分散计入 GPU/CPU/机箱项；ABF 载板短缺是 2026 主题之一',
    players: ['载板：欣兴、Ibiden', 'PCB：金像电、沪电(C)', 'VRM：MPS、瑞萨、英飞凌'],
    conf: 'B',
  },
  'mlcc': {
    name: 'MLCC 与被动元件',
    cat: '元件',
    desc: '板上成千上万颗陶瓷电容做瞬时供电缓冲。Bernstein 原话：MLCC 是热门话题但"无法形成高置信度观点"——自上而下很难测算。AI 板卡用量是普通服务器数倍，方向确定、数字待补。',
    role: '供电质量的"毛细血管"',
    shape: '芯片周围密密麻麻的小黑点',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '待补充（两份报告都未单列）',
    players: ['村田', '三星电机', '国巨', '太诱(C)', '风华高科(C)'],
    conf: 'C',
  },
  'osfp': {
    name: '前面板 OSFP 笼 / 光模块',
    cat: '接口',
    desc: '托盘前面板的 OSFP 笼，插 800G/1.6T 光模块连到柜外 leaf 交换机（scale-out）。光模块单价高（1.6T 约 $850 成本价）但只用在柜间——柜内被铜缆替代了。CPO（共封装光学）是下一个形态变化。',
    role: 'scale-out 网络的物理端口',
    shape: '前面板金属笼 + 带拉环的光模块',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入 scale-out / 集群层（详见集群网络视图）',
    players: ['中际旭创', '新易盛', 'Coherent', '天孚通信（器件）(C)', 'Fabrinet(C)'],
    conf: 'A',
  },
  'fan': {
    name: '风扇（托盘前段）',
    cat: '散热',
    desc: '托盘 85% 热量走液冷，但前部的 NIC/DPU/管理板/存储仍是风冷，每托盘 8 个风扇。提醒：NVL72 不是 100% 液冷。',
    role: '前段元件的风冷',
    shape: '托盘中段一排小风扇',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入机箱项',
    players: ['台达', 'AVC 奇鋐', 'Nidec(C)'],
    conf: 'B',
  },

  // ===== NVSwitch 托盘内部 =====
  'nvswitch-chip': {
    name: 'NVSwitch5 芯片',
    cat: '芯片',
    desc: '每托盘 2 颗 28.8Tb/s NVSwitch5，9 个托盘 18 颗构成全柜 72 GPU 无阻塞全互联。交换芯片毛利率极高（~80%），交换环节在利润池里的分量大于 capex 占比。',
    role: 'NVLink 流量的十字路口',
    shape: '托盘中央两颗大芯片，各自压冷板',
    value: { perRackK: 184, bGW: 1.1, pct: 2.7 }, vrK: 253,
    valueNote: '含芯片+设计+整机毛利',
    players: ['NVIDIA', '代工：台积电', '对照：博通 Tomahawk（以太网路线）'],
    conf: 'A',
  },
  'backplane-connector': {
    name: '背板连接器',
    cat: '接口',
    desc: '托盘背面与铜缆背板对接的高密度连接器。每个交换托盘背后 4 个 144 差分对连接器（576 DP）。安费诺是代表玩家。',
    role: '托盘与背板缆线的对接口',
    shape: '托盘后缘一排金属高密度插座',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入铜缆+背板项',
    players: ['安费诺 Amphenol', 'TE(C)', '立讯精密(C)'],
    conf: 'A',
  },

  // ===== 园区层：电力链路节点（按 SemiAnalysis Datacenter Anatomy Part 1）=====
  // 价值量都计入园区 power-distribution / backup-power 项，这里只标注链路位置和角色
  'substation': {
    name: '现场变电站（HV→MV）',
    cat: '电力链路',
    desc: '园区入口的第一站：从电网拉来的高压（138/230/345kV）经高压变压器降到中压（11/22/33kV）。一个 150MW 园区典型配 2× 80MVA 变压器或 3× N+1 冗余。AI 时代的瓶颈：HV 变压器交付期已超 12 个月，关键材料 GOES（取向硅钢）全球产能有限——这是当前数据中心建设的硬约束之一，比芯片紧缺更难解。',
    role: '把电网级高压降到园区可用的中压',
    shape: '园区外侧的露天大型变压器矩阵 + 隔离开关',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价值量计入园区"配电系统"项；HV 变压器单价数百万美元/台',
    players: ['ABB', '西门子能源', '伊顿', '日立能源(C)', '思源电气(C)', '中国西电(C)', '特变电工(C)'],
    conf: 'B',
  },
  'mv-switchgear': {
    name: '中压开关柜',
    cat: '电力链路',
    desc: '把中压电分配到园区各 Pod。Pod 是数据中心的最小独立配电单元，常见 1.6/2/2.5MW 三档，每个 Pod 自带变压器/柴发/UPS/开关柜。开关柜的核心是断路器——故障时切断电流保护下游设备。',
    role: '中压配电的总枢纽',
    shape: '建筑内一排金属柜，每个柜门带断路器手柄和指示灯',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入"中低压开关柜"$110K/柜；Vertiv 报告数字',
    players: ['伊顿', '施耐德', 'ABB', 'Vertiv'],
    conf: 'B',
  },
  'mv-transformer': {
    name: '中压变压器（Pod 级）',
    cat: '电力链路',
    desc: '每个 Pod 的入口变压器：典型 2.5-3 MVA，把 33/22/11kV 中压降到美国常用的 415V 三相低压。降压后电流暴增（230kV 的 350A 到低压侧约 4000-5000A），低压侧导线/母排都很粗。',
    role: 'Pod 级降压',
    shape: '建筑内的箱式变压器，比 HV 变压器小但仍有人高',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入"变压器"$306K/柜（HV+MV 合并）',
    players: ['伊顿', '施耐德', 'ABB', '日立能源(C)', '金盘科技(C)'],
    conf: 'B',
  },
  'ats': {
    name: 'ATS 自动转换开关',
    cat: '电力链路',
    desc: '市电与柴发之间的切换开关。市电断电时，ATS 检测到失压→给柴发发启动信号→柴发启动稳定（约 60 秒）→ATS 切到柴发供电。这 60 秒的空缺由 UPS 顶住。Tier 4 数据中心还会用基于电力电子的 STS（静态转换开关）实现毫秒级切换。',
    role: '市电↔柴发的物理切换',
    shape: '低压开关柜旁边的中等机柜，里面是大型机械接触器',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入"PDU/ATS/STS等"$29K/柜',
    players: ['伊顿', '施耐德', 'ABB', 'SOCOMEC(C)', 'Cummins(C)'],
    conf: 'B',
  },
  'lv-switchgear': {
    name: '低压开关柜',
    cat: '电力链路',
    desc: '415V 低压侧的总配电柜，下游接 UPS、机房空调、照明、消防等所有低压负载。AI 时代电流极大（一个 2MW Pod 低压侧 4000-5000A），母排载流和散热都被推到极限。',
    role: '低压侧总配电',
    shape: '建筑内一排大型金属柜，柜门密布断路器面板',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入"中低压开关柜"$110K/柜',
    players: ['伊顿', '施耐德', 'ABB', 'Vertiv'],
    conf: 'B',
  },
  'ups': {
    name: 'UPS（不间断电源）',
    cat: '电力链路',
    desc: '断电瞬间的无缝衔接：响应时间 <10ms，电池续航通常 5-10 分钟（足够柴发启动稳定）。损耗 3-5% 是非 IT 耗电的主要来源之一（电力系统占非 IT 用电 15-30%），VFD（变频驱动）待机模式可达 >99% 效率但增加几毫秒切换。Vertiv 模块化方案：核心 200/400 kVA × 最多 10 模块/台 × 最多 8 并联 = 单系统 27MW。冗余通常做 2N（A/B 两套）或 N+2C（多台小 UPS+冗余）。',
    role: '应对毫秒到分钟级断电',
    shape: '机房内一排大型机柜，里面是 IGBT 逆变器+整流器+电池',
    value: { perRackK: 258, bGW: 1.5, pct: 3.8 },
    valueNote: 'UPS 硬件项；Vertiv/Schneider/Eaton 三家主导全球市场',
    players: ['Vertiv', '施耐德', '伊顿', '台达', 'Socomec(C)', '科华数据(C)'],
    conf: 'A',
  },
  'sts': {
    name: 'STS 静态转换开关',
    cat: '电力链路',
    desc: 'UPS 故障或维护时，从主路切到旁路供电的电力电子开关，切换时间毫秒级（远快于 ATS 的物理切换）。Tier 4（最高等级，"fault tolerant"）数据中心常用。',
    role: 'UPS 的旁路切换',
    shape: 'UPS 旁边的小机柜',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入"PDU/ATS/STS等"项',
    players: ['Vertiv', '施耐德', 'SOCOMEC(C)', 'Cyber Power(C)'],
    conf: 'C',
  },
  'bbu': {
    name: 'BBU（机柜级电池备份）',
    cat: '电力链路',
    desc: '锂电池组直接进机柜，绕过中央 UPS——本质上是"in-rack UPS"。优点：DC 直接供电效率更高，不需要 A/B 两套 UPS 电池，总容量减半；缺点：机柜里放锂电池要重做消防方案（集中电池间的防火管控更容易做）。AI 时代是结构性增长方向：Rubin 时代电源价值量从 GB200 的 $44K/柜涨到 VR 的 $150K/柜，BBU 是核心驱动之一。',
    role: 'AI 时代的供电架构变革',
    shape: '机柜内 1-2U 的电池模块，与电源架并排',
    value: { perRackK: 14, bGW: 0.08, pct: 0.2 },
    valueNote: 'GB200 口径 $14K/柜；VR 时代显著放大，Bernstein 看好 Delta 受益',
    players: ['台达', 'Vertiv', '宁德时代(C)', '亿纬锂能(C)', '欣旺达(C)'],
    conf: 'B',
  },
  'busway': {
    name: '母线槽（Busway）',
    cat: '电力链路',
    desc: '机房内沿天花板架设的金属导槽，里面跑铜/铝排，每隔几米开一个 tap-off（取电口），柔性电缆 whip 从 tap-off 接到机柜。比传统电缆桥架更灵活：机柜搬位置只需挪 tap-off 位置，不用重新拉线。AI 时代单机柜 130kW+，母线槽载流要求大幅提升。',
    role: '机房内"电力高速路"',
    shape: '天花板下方一长条银色金属槽',
    value: { perRackK: 50, bGW: 0.3, pct: 0.7 },
    valueNote: '"母线槽 Busway"$50K/柜；Vertiv/Starline/Legrand 三家主导',
    players: ['Vertiv', 'Legrand', 'Starline(C)', 'Schneider', '威腾电气(C)'],
    conf: 'A',
  },
  'pdu': {
    name: '机柜 PDU（垂直配电单元）',
    cat: '电力链路',
    desc: '机柜里两条垂直延伸的"插线板"，A 侧 + B 侧，对应 2N 双路冗余——任何一路单点故障不影响业务。AI 机柜密度大幅提升后，PDU 的载流和监控需求都升级（智能 PDU 带每口能耗遥测）。',
    role: '机柜内的最末端配电',
    shape: '机柜后部两根竖直长条，密布 C13/C19/Anderson 插孔',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入"PDU/ATS/STS等"项',
    players: ['Vertiv', 'Legrand', 'Raritan(C)', 'Server Technology(C)'],
    conf: 'B',
  },

  // ===== 园区层：冷却链路（已有部分）=====
  'cdu': {
    name: 'CDU（冷量分配单元）',
    cat: '冷却链路',
    desc: '液冷的"中转站"：液-液换热器 + 水泵 + 控制，内环接机柜冷板回路，外环接设施水。机房级 CDU 单台容量 >1MW（Vertiv 参考设计用 250kW 柜内 CDU / 1.3MW 列间 CDU 两种形态）。L2L 比 L2A sidecar（70-140kW，靠散热器+风扇）经济得多，新建大规模 AI 机房基本都走 L2L。',
    role: '把柜内冷却液的热量交换到设施水',
    shape: '机柜大小的金属柜（列间式）或柜底模块（柜内式），连着粗水管',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入园区热管理项',
    players: ['Vertiv', '台达', 'Boyd(C)', 'Motivair(C)', '英维克(C)'],
    conf: 'B',
  },
  'chiller': {
    name: '冷机（Chiller）',
    cat: '冷却链路',
    desc: '数据中心除 IT 外最耗电的单一设备（冷却占非 IT 耗电的 60-80%，冷机是大头）。压缩制冷循环把设施水降温，水冷离心式单台可达 15-20MW，COP 约 7。液冷允许更高的水温，能降低冷机能耗甚至部分时段"免费冷却"。',
    role: '主动制冷，决定 PUE 的关键',
    shape: '厂房内的大型卧式机组（水冷）或屋顶成排带风扇的机组（风冷）',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入园区热管理项',
    players: ['Carrier(C)', 'Trane(C)', 'York/JCI(C)', '美的/格力工业(C)'],
    conf: 'B',
  },
  'cooling-tower': {
    name: '冷却塔',
    cat: '冷却链路',
    desc: '热链路的终点：把冷机冷凝器的热量蒸发/对流排到大气。和水冷冷机配套，耗水量是数据中心环保争议的来源（也有干冷器等省水替代）。',
    role: '热量最终排向大气',
    shape: '园区外侧成排的方塔，顶部大风扇',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入园区热管理项',
    players: ['BAC(C)', 'SPX(C)', 'Evapco(C)'],
    conf: 'B',
  },

  // ===== 集群层 =====
  'nvlink-domain': {
    name: 'NVLink 域（柜内 scale-up）',
    cat: '集群网络',
    desc: '一个 NVL72 = 一个 NVLink 域：72 颗 GPU 每颗 900GB/s 互联，全部走柜内铜缆，零光模块。这是"纵向扩展"的边界——域内通信快一个数量级，域间就要走光了。',
    role: '单柜内的超高速互联',
    shape: '柜内 5184 根铜缆 + 18 颗 NVSwitch 芯片',
    value: { perRackK: 409, bGW: 2.4, pct: 6.0 }, vrK: 871,
    valueNote: 'scale-up 合计（交换托盘+铜缆+背板）≈ 机柜成本 8%',
    players: ['NVIDIA', '安费诺', '立讯(C)'],
    conf: 'A',
  },
  'ib-fabric': {
    name: '柜间网络（scale-out fabric）',
    cat: '集群网络',
    desc: '把 N 个机柜连成训练集群：每柜的 ConnectX 网卡经光模块上到 leaf 交换机，再到 spine（胖树拓扑，约每 4 柜配 9 台 leaf）。选择题：英伟达 InfiniBand/SpectrumX（贵）vs 博通方案以太网（便宜）——超大客户最常见的偏离就在这。8 柜 = 1 个 DGX SuperPOD scalable unit。',
    role: '集群层面的"横向扩展"',
    shape: '独立网络机柜 + 柜间成捆的光纤',
    value: { perRackK: 341, bGW: 2.0, pct: 5.0 }, vrK: 396,
    valueNote: 'scale-out ≈ 机柜成本 5%；另有存储网/带外管理网两张独立网络',
    players: ['NVIDIA（IB/SpectrumX）', 'Arista+博通（以太网）', '思科(C)'],
    conf: 'A',
  },
  'cluster-optics': {
    name: '光模块（柜间互联）',
    cat: '集群网络',
    desc: '光模块只出现在柜间（柜内被铜缆消灭了）。800G→1.6T 演进中，1.6T 成本价约 $850/个。一个柜对外的上行需求随 GPU 代际增长。光电转换的位置正在发生革命：可插拔→LPO→NPO→CPO，点击进入光互联技术视图看四条路线的结构对比。',
    role: '柜间高速信号的电光转换',
    shape: '交换机和托盘前面板上带拉环的小金属块',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '计入 scale-out 项；用量与网络拓扑（rail-optimized 与否）强相关',
    players: ['中际旭创', '新易盛', 'Coherent', 'Fabrinet(C)', '天孚通信(C)'],
    conf: 'B',
    action: 'enterOptics',
  },

  // ============================================================
  // 光互联技术视图（V2.2 新增）：可插拔 → LPO → NPO → CPO
  // 数据来源：公开技术资料（NVIDIA GTC、台积电 COUPE、LPO MSA、
  // Broadcom Davisson 等），价格字段待补，结构置信度 B
  // ============================================================
  'optics-pluggable': {
    name: '方案①：传统可插拔光模块（DSP Pluggable）',
    cat: '光互联方案',
    desc: '当前绝对主力（2026 年 800G+ 可插拔市场约 $260 亿，CPO 仅占 AI 光模块 ~0.5%）。光模块插在交换机前面板，模块内含完整 DSP：信号从交换 ASIC 出发，经几十厘米 PCB 走线到前面板，DSP 负责重整劣化的信号。代价是功耗——1.6T 模块约 30W，其中 DSP 链路（ADC/DAC+DSP+FEC+CDR）占大头；一台 51.2T 交换机仅光模块就 800W-1500W，占系统功耗 40%+，前面板散热已逼近风冷极限。优点同样关键：可插拔=坏了换新不停机，多源供应=价格竞争。',
    role: '现状基准：灵活可维护，但功耗到顶了',
    shape: '交换机前面板一排带拉环的金属小块，模块内部：DSP 芯片 + 激光器 + 调制器 + 探测器',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '1.6T 模块成本价约 $850（SemiAnalysis）；价格细节待补',
    players: ['中际旭创', '新易盛', 'Coherent', 'Marvell/博通（DSP 芯片）', 'Fabrinet'],
    conf: 'B',
  },
  'optics-lpo': {
    name: '方案②：LPO 线性可插拔',
    cat: '光互联方案',
    desc: '"最小改动"路线：把模块里的 DSP 整个去掉，只留线性 Driver 和 TIA（模拟放大），靠交换 ASIC 自己的 SerDes 直接驱动光器件。功耗比 DSP 方案降 30-50%，延迟更低，而且保住了两样东西：可插拔形态（运维不变）和多源供应（光模块厂商的生意还在）。代价是对 ASIC SerDes 和通道质量要求苛刻，传输距离受限。Arista 创始人 Bechtolsheim 是旗手，LPO MSA 联盟推进标准化。产业博弈视角：LPO 是光模块厂商阵营对 CPO（芯片厂垄断生态）的反击。',
    role: '去 DSP 但保可插拔：光模块厂商的防线',
    shape: '外观和普通光模块一样，拆开看里面少了最大的那颗 DSP 芯片',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补；BOM 比 DSP 模块少一颗几十美元的 DSP',
    players: ['中际旭创', '新易盛', 'Macom/Semtech（Driver/TIA）(C)', 'Arista（整机推动）'],
    conf: 'B',
  },
  'optics-npo': {
    name: '方案③：NPO 近封装光学',
    cat: '光互联方案',
    desc: '过渡形态：光引擎从前面板搬进机箱，放在交换 ASIC 附近的独立基板上（电链路从几十厘米缩到几厘米），前面板只留光纤接口。和它类似的 OBO（板载光学）把光引擎焊在主板上。行业评价是"两头不讨好"——封装复杂度接近 CPO，但功耗带宽收益不如 CPO，可插拔性又没了。作为 CPO 生态成熟前的台阶存在，部分系统厂商在推。',
    role: '从可插拔到 CPO 之间的台阶',
    shape: '机箱内 ASIC 周围一圈独立的小光引擎模组，前面板只剩光纤口',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补',
    players: ['系统厂商主导（思科等曾试水）(C)'],
    conf: 'C',
  },
  'optics-cpo': {
    name: '方案④：CPO 共封装光学',
    cat: '光互联方案',
    desc: '终局形态：光引擎和交换 ASIC 封装在同一基板上，电气路径从几十厘米缩到几毫米，1.6T 端口功耗 30W→9W（降 70%，黄仁勋 GTC 原话）。激光器单独拿出来做成前面板可插拔的 ELS（外置激光源）——激光器是最容易坏的部分，可插拔保住运维性。已落地：NVIDIA Quantum-X800 CPO 交换机 2025H2 出货（115.2T，18 个 1.6T 硅光引擎），Spectrum-X Photonics 以太网 2026H2 量产，Broadcom Tomahawk 6 "Davisson" 同步竞争。节奏要拿捏：2026 年 CPO 占 AI 光模块仅 ~0.5%，LightCounting 预测 2027 年 800G/1.6T 端口中 CPO 占近 30%——放量是 2027 后的事。2028 年 Feynman 世代 CPO 进 NVLink 交换机（NVL1152），那才是真正的大变局。',
    role: '功耗的终极答案，也是供应链的重新洗牌',
    shape: '交换芯片周围环绕一圈光引擎（NVIDIA：6 组件 ×3 个 1.6T 引擎），前面板全是 MPO 光纤口 + 一排金色 ELS 激光模块',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补；产业链价值重构：代工/封装受益，纯模块组装承压',
    players: ['NVIDIA + 台积电 COUPE（EIC+PIC 3D 堆叠）', 'Broadcom', '激光器：Lumentum（首发独家）、Coherent（26 末二供，NVDA 各投 $20 亿）', '封测：日月光 SPIL', 'FAU/光纤：天孚、康宁、SENKO、住友'],
    conf: 'B',
  },
  // 光互联子部件
  'opt-dsp': {
    name: 'DSP（光模块里的数字信号处理器）',
    cat: '光互联部件',
    desc: '可插拔模块的"心脏"也是"电老虎"：把走了几十厘米 PCB 已经劣化的电信号重新整形（ADC/DAC 3-4W + DSP 核 2-3W + FEC 1-2W + CDR 1W，每 100G 通道 7-10W）。LPO 和 CPO 的共同点就是干掉它。DSP 芯片本身是 Marvell/博通的高毛利生意——这也是路线之争背后的利益格局。',
    role: '信号重整，占模块功耗大头',
    shape: '光模块拆开后最大的那颗芯片',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补',
    players: ['Marvell', '博通'],
    conf: 'B',
  },
  'opt-engine': {
    name: '硅光引擎（Optical Engine）',
    cat: '光互联部件',
    desc: 'CPO 的核心单元：PIC（光子集成电路，含微环调制器 MRM）+ EIC（电子集成电路，Driver/TIA）3D 堆叠。NVIDIA 方案：每个 1.6T 引擎 = 8×200G MRM 通道，台积电 COUPE 平台（65nm EIC 用 SoIC-X 堆在 PIC 上），每个引擎配 20 根光纤的 FAU（8 收 8 发 4 激光），单台交换机 1440 根光纤。台积电路线图：2026 年 6.4T 引擎与交换芯片合封，未来 12.8T 用于 XPU 互联。',
    role: '电信号变光信号的最小完整单元',
    shape: '交换芯片旁边指甲盖大小的方块，引出一束光纤',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补；COUPE 产能是 2026-27 关键变量',
    players: ['台积电（COUPE）', '日月光 SPIL（封测）', 'FAU：天孚通信'],
    conf: 'B',
  },
  'opt-els': {
    name: 'ELS 外置激光源',
    cat: '光互联部件',
    desc: 'CPO 把激光器从光引擎里拿出来，做成前面板可插拔的模块——激光器是光链路里最容易失效的器件，外置可插拔保住了运维性（坏了换激光，不用换交换机）。代价：激光要经外部耦合进硅光引擎，1.8-3dB 耦合损耗使激光器功耗增加 50-100%。这是 CPO 时代激光器厂商的新形态产品。',
    role: 'CPO 的"灯泡"，可插拔可更换',
    shape: '前面板一排金色小模块，每个驱动多个光引擎',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补；Lumentum 首发独家、Coherent 预计 2026 末加入',
    players: ['Lumentum', 'Coherent', '（NVIDIA 向两家各投资 $20 亿）'],
    conf: 'B',
  },
  'opt-mpo': {
    name: 'MPO 光纤连接器 / 光纤',
    cat: '光互联部件',
    desc: 'CPO 交换机前面板不再有光模块，全是 MPO 光纤口（Quantum-X800：144 个 MPO 口）。光纤本身用量暴增——单台 1440 根，光纤/连接器/清洁运维都是新需求。康宁、SENKO、住友电工在 NVIDIA 官方生态名单里。',
    role: '光信号的物理通道',
    shape: '前面板密集的方形光纤插口 + 机柜间成捆的光纤',
    value: { perRackK: null, bGW: null, pct: null },
    valueNote: '价格待补',
    players: ['康宁', 'SENKO', '住友电工', '波若威(C)', 'Fabrinet'],
    conf: 'B',
  },
};
